# default: https://github.com/mpv-player/mpv/blob/master/etc/input.conf
# List of commands and further details: DOCS/man/input.rst
# List of special keys: --input-keylist
# Keybindings testing mode: mpv --input-test --force-window --idle

# YT-like
l seek 10
k cycle pause
j seek -10
c script-binding select/select-sid
# note: YT's c is same as:
# v cycle sub-visibility

# note: this disables
#l ab-loop                              # set/clear A-B loop points

Shift+m cycle-values audio-channels "auto-safe" "mono"
