# set in the player itself: ` -> set opt val

screenshot-directory=~/Pictures

# don't close when done playing
keep-open=yes

# feels better on kwin
x11-bypass-compositor=no

# don't try to show too big windows
autofit-larger=1920x1080

# 4K is too much
# split streams sometimes aren't available (e.g. livestreams)
ytdl-format='bestvideo*[height<=1440]+bestaudio / best[height<=1440]'

# 'AMD Radeon Graphics (RADV RENOIR)' (GPU 0, PCI ID 1002:1638, UUID 00000000-0700-0000-0000-000000000000)
vulkan-device=00000000-0700-0000-0000-000000000000

[cache]
profile-cond=demuxer_via_network

# deleted after exit anyway...
# cache=yes
# cache-on-disk=yes

# cache more than just 150M
demuxer-max-bytes=3000M
